-- MySQL Script generated by MySQL Workbench
-- seg 10 jun 2019 13:23:07 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema pedido
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pedido
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pedido` DEFAULT CHARACTER SET utf8 ;
USE `pedido` ;

-- -----------------------------------------------------
-- Table `pedido`.`fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedido`.`fornecedor` (
  `idfornecedor` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `telefone` VARCHAR(15) NULL DEFAULT NULL,
  `logradouro` VARCHAR(200) NULL DEFAULT NULL,
  `numero` VARCHAR(10) NULL DEFAULT NULL,
  `complemento` VARCHAR(15) NULL DEFAULT NULL,
  `bairro` VARCHAR(45) NULL DEFAULT NULL,
  `cidade` VARCHAR(45) NULL DEFAULT NULL,
  `uf` VARCHAR(2) NULL DEFAULT NULL,
  `cep` VARCHAR(10) NULL DEFAULT NULL,
  `regras` VARCHAR(255) NULL DEFAULT NULL,
  `razao` VARCHAR(45) NULL DEFAULT NULL,
  `inscricao` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`idfornecedor`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pedido`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedido`.`usuario` (
  `idusuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `senha` VARCHAR(45) NULL DEFAULT NULL,
  `telefone` VARCHAR(15) NULL DEFAULT NULL,
  `logradouro` VARCHAR(200) NULL DEFAULT NULL,
  `numero` VARCHAR(10) NULL DEFAULT NULL,
  `complemento` VARCHAR(15) NULL DEFAULT NULL,
  `bairro` VARCHAR(45) NULL DEFAULT NULL,
  `cidade` VARCHAR(45) NULL DEFAULT NULL,
  `uf` VARCHAR(2) NULL DEFAULT NULL,
  `cep` VARCHAR(10) NULL DEFAULT NULL,
  `cliente` TINYINT(4) NULL DEFAULT 1,
  `cpf` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pedido`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedido`.`pedido` (
  `idPedido` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario_idusuario` INT(11) NOT NULL,
  `aprovado` TINYINT(4) NULL DEFAULT NULL,
  `observacao` VARCHAR(200) NULL DEFAULT NULL,
  `totalgeral` DECIMAL(10,2) NULL DEFAULT 0.00,
  `formapagamento` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`idPedido`),
  INDEX `fk_Pedido_Usuario1_idx` (`usuario_idusuario` ASC),
  CONSTRAINT `fk_Pedido_Usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `pedido`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pedido`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedido`.`produto` (
  `idproduto` INT(11) NOT NULL AUTO_INCREMENT,
  `fornecedor_idfornecedor` INT(11) NOT NULL,
  `descricao` VARCHAR(200) NULL DEFAULT NULL,
  `preco` FLOAT NULL DEFAULT NULL,
  `observacao` VARCHAR(100) NULL DEFAULT NULL,
  `inativo` TINYINT(1) NULL DEFAULT 0,
  `imagem` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`idproduto`),
  INDEX `fk_Produto_fornecedor1_idx` (`fornecedor_idfornecedor` ASC),
  CONSTRAINT `fk_Produto_fornecedor1`
    FOREIGN KEY (`fornecedor_idfornecedor`)
    REFERENCES `pedido`.`fornecedor` (`idfornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pedido`.`itemPedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedido`.`itemPedido` (
  `iditempedido` INT(11) NOT NULL AUTO_INCREMENT,
  `pedido_idpedido` INT(11) NOT NULL,
  `produto_idproduto` INT(11) NOT NULL,
  `qtde` INT(11) NULL DEFAULT NULL,
  `observacao` VARCHAR(100) NULL DEFAULT NULL,
  `valor` DECIMAL(10,2) NULL DEFAULT NULL,
  `total` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`iditempedido`),
  INDEX `fk_itemPedido_Pedido1_idx` (`pedido_idpedido` ASC),
  INDEX `fk_itemPedido_Produto1_idx` (`produto_idproduto` ASC),
  CONSTRAINT `fk_itemPedido_Pedido1`
    FOREIGN KEY (`pedido_idpedido`)
    REFERENCES `pedido`.`pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_itemPedido_Produto1`
    FOREIGN KEY (`produto_idproduto`)
    REFERENCES `pedido`.`produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8
COMMENT = '	';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
